# Generated by Django 5.2.1 on 2025-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregarservicio',
            fields=[
                ('idagregarservicio', models.AutoField(db_column='IdAgregarServicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
            options={
                'db_table': 'agregarservicio',
            },
        ),
    ]
